# Generated by Django 4.2.16 on 2024-11-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0002_debt_duration_date_returndebt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
