# Generated by Django 4.2.16 on 2024-11-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
